// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: proto/manager/server.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConsumerGroup string `protobuf:"bytes,1,opt,name=ConsumerGroup,proto3" json:"ConsumerGroup,omitempty"`
	// Types that are assignable to Command:
	//
	//	*ClientRequest_Ack
	//	*ClientRequest_Keepalive
	Command isClientRequest_Command `protobuf_oneof:"Command"`
}

func (x *ClientRequest) Reset() {
	*x = ClientRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_manager_server_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientRequest) ProtoMessage() {}

func (x *ClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manager_server_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientRequest.ProtoReflect.Descriptor instead.
func (*ClientRequest) Descriptor() ([]byte, []int) {
	return file_proto_manager_server_proto_rawDescGZIP(), []int{0}
}

func (x *ClientRequest) GetConsumerGroup() string {
	if x != nil {
		return x.ConsumerGroup
	}
	return ""
}

func (m *ClientRequest) GetCommand() isClientRequest_Command {
	if m != nil {
		return m.Command
	}
	return nil
}

func (x *ClientRequest) GetAck() *ClientRequest_MarkIdentifier {
	if x, ok := x.GetCommand().(*ClientRequest_Ack); ok {
		return x.Ack
	}
	return nil
}

func (x *ClientRequest) GetKeepalive() uint32 {
	if x, ok := x.GetCommand().(*ClientRequest_Keepalive); ok {
		return x.Keepalive
	}
	return 0
}

type isClientRequest_Command interface {
	isClientRequest_Command()
}

type ClientRequest_Ack struct {
	Ack *ClientRequest_MarkIdentifier `protobuf:"bytes,2,opt,name=ack,proto3,oneof"`
}

type ClientRequest_Keepalive struct {
	Keepalive uint32 `protobuf:"varint,3,opt,name=keepalive,proto3,oneof"`
}

func (*ClientRequest_Ack) isClientRequest_Command() {}

func (*ClientRequest_Keepalive) isClientRequest_Command() {}

type ServerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Payload []byte `protobuf:"bytes,1,opt,name=Payload,proto3" json:"Payload,omitempty"`
	TaskID  int32  `protobuf:"varint,2,opt,name=TaskID,proto3" json:"TaskID,omitempty"`
}

func (x *ServerResponse) Reset() {
	*x = ServerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_manager_server_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerResponse) ProtoMessage() {}

func (x *ServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manager_server_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerResponse.ProtoReflect.Descriptor instead.
func (*ServerResponse) Descriptor() ([]byte, []int) {
	return file_proto_manager_server_proto_rawDescGZIP(), []int{1}
}

func (x *ServerResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ServerResponse) GetTaskID() int32 {
	if x != nil {
		return x.TaskID
	}
	return 0
}

type OutcomeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResponsePayload []byte `protobuf:"bytes,1,opt,name=ResponsePayload,proto3" json:"ResponsePayload,omitempty"`
	TaskID          int32  `protobuf:"varint,2,opt,name=TaskID,proto3" json:"TaskID,omitempty"`
}

func (x *OutcomeRequest) Reset() {
	*x = OutcomeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_manager_server_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OutcomeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutcomeRequest) ProtoMessage() {}

func (x *OutcomeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manager_server_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutcomeRequest.ProtoReflect.Descriptor instead.
func (*OutcomeRequest) Descriptor() ([]byte, []int) {
	return file_proto_manager_server_proto_rawDescGZIP(), []int{2}
}

func (x *OutcomeRequest) GetResponsePayload() []byte {
	if x != nil {
		return x.ResponsePayload
	}
	return nil
}

func (x *OutcomeRequest) GetTaskID() int32 {
	if x != nil {
		return x.TaskID
	}
	return 0
}

type OutcomeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *OutcomeResponse) Reset() {
	*x = OutcomeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_manager_server_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OutcomeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutcomeResponse) ProtoMessage() {}

func (x *OutcomeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manager_server_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutcomeResponse.ProtoReflect.Descriptor instead.
func (*OutcomeResponse) Descriptor() ([]byte, []int) {
	return file_proto_manager_server_proto_rawDescGZIP(), []int{3}
}

type ClientRequest_MarkIdentifier struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ClientRequest_MarkIdentifier) Reset() {
	*x = ClientRequest_MarkIdentifier{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_manager_server_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientRequest_MarkIdentifier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientRequest_MarkIdentifier) ProtoMessage() {}

func (x *ClientRequest_MarkIdentifier) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manager_server_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientRequest_MarkIdentifier.ProtoReflect.Descriptor instead.
func (*ClientRequest_MarkIdentifier) Descriptor() ([]byte, []int) {
	return file_proto_manager_server_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ClientRequest_MarkIdentifier) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_proto_manager_server_proto protoreflect.FileDescriptor

var file_proto_manager_server_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2f,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x6d, 0x61,
	0x6e, 0x61, 0x67, 0x65, 0x72, 0x22, 0xbd, 0x01, 0x0a, 0x0d, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x24, 0x0a, 0x0d, 0x43, 0x6f, 0x6e, 0x73, 0x75,
	0x6d, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d,
	0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x39, 0x0a,
	0x03, 0x61, 0x63, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x6d, 0x61, 0x6e,
	0x61, 0x67, 0x65, 0x72, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x2e, 0x4d, 0x61, 0x72, 0x6b, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65,
	0x72, 0x48, 0x00, 0x52, 0x03, 0x61, 0x63, 0x6b, 0x12, 0x1e, 0x0a, 0x09, 0x6b, 0x65, 0x65, 0x70,
	0x61, 0x6c, 0x69, 0x76, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x48, 0x00, 0x52, 0x09, 0x6b,
	0x65, 0x65, 0x70, 0x61, 0x6c, 0x69, 0x76, 0x65, 0x1a, 0x20, 0x0a, 0x0e, 0x4d, 0x61, 0x72, 0x6b,
	0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x42, 0x09, 0x0a, 0x07, 0x43, 0x6f,
	0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x22, 0x42, 0x0a, 0x0e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x50, 0x61, 0x79, 0x6c, 0x6f,
	0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61,
	0x64, 0x12, 0x16, 0x0a, 0x06, 0x54, 0x61, 0x73, 0x6b, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x54, 0x61, 0x73, 0x6b, 0x49, 0x44, 0x22, 0x52, 0x0a, 0x0e, 0x4f, 0x75, 0x74,
	0x63, 0x6f, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x0f, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x0f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50, 0x61,
	0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x54, 0x61, 0x73, 0x6b, 0x49, 0x44, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x54, 0x61, 0x73, 0x6b, 0x49, 0x44, 0x22, 0x11, 0x0a,
	0x0f, 0x4f, 0x75, 0x74, 0x63, 0x6f, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x32, 0x8b, 0x01, 0x0a, 0x07, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x12, 0x40, 0x0a, 0x07,
	0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x12, 0x16, 0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65,
	0x72, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x17, 0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x12, 0x3e,
	0x0a, 0x07, 0x4f, 0x75, 0x74, 0x63, 0x6f, 0x6d, 0x65, 0x12, 0x17, 0x2e, 0x6d, 0x61, 0x6e, 0x61,
	0x67, 0x65, 0x72, 0x2e, 0x4f, 0x75, 0x74, 0x63, 0x6f, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x18, 0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x4f, 0x75, 0x74,
	0x63, 0x6f, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x06,
	0x5a, 0x04, 0x2e, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_manager_server_proto_rawDescOnce sync.Once
	file_proto_manager_server_proto_rawDescData = file_proto_manager_server_proto_rawDesc
)

func file_proto_manager_server_proto_rawDescGZIP() []byte {
	file_proto_manager_server_proto_rawDescOnce.Do(func() {
		file_proto_manager_server_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_manager_server_proto_rawDescData)
	})
	return file_proto_manager_server_proto_rawDescData
}

var file_proto_manager_server_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_manager_server_proto_goTypes = []interface{}{
	(*ClientRequest)(nil),                // 0: manager.ClientRequest
	(*ServerResponse)(nil),               // 1: manager.ServerResponse
	(*OutcomeRequest)(nil),               // 2: manager.OutcomeRequest
	(*OutcomeResponse)(nil),              // 3: manager.OutcomeResponse
	(*ClientRequest_MarkIdentifier)(nil), // 4: manager.ClientRequest.MarkIdentifier
}
var file_proto_manager_server_proto_depIdxs = []int32{
	4, // 0: manager.ClientRequest.ack:type_name -> manager.ClientRequest.MarkIdentifier
	0, // 1: manager.Manager.Connect:input_type -> manager.ClientRequest
	2, // 2: manager.Manager.Outcome:input_type -> manager.OutcomeRequest
	1, // 3: manager.Manager.Connect:output_type -> manager.ServerResponse
	3, // 4: manager.Manager.Outcome:output_type -> manager.OutcomeResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_manager_server_proto_init() }
func file_proto_manager_server_proto_init() {
	if File_proto_manager_server_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_manager_server_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_manager_server_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_manager_server_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OutcomeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_manager_server_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OutcomeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_manager_server_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientRequest_MarkIdentifier); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_manager_server_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*ClientRequest_Ack)(nil),
		(*ClientRequest_Keepalive)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_manager_server_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_manager_server_proto_goTypes,
		DependencyIndexes: file_proto_manager_server_proto_depIdxs,
		MessageInfos:      file_proto_manager_server_proto_msgTypes,
	}.Build()
	File_proto_manager_server_proto = out.File
	file_proto_manager_server_proto_rawDesc = nil
	file_proto_manager_server_proto_goTypes = nil
	file_proto_manager_server_proto_depIdxs = nil
}
